server:
  port: 9997
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/
spring:
  application:
    name: nlxx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.31.35:3306/nlxx?characterEncoding=utf-8
    username: wypawj
    password: 123
  redis:
    host: 121.199.31.35
  rabbitmq:
    host: 121.199.31.35

mybatis:
  mapperLocations: classpath:mappers/*.xml