server:
  port: 9999

eureka:
  client:
    #是否将本服务 注册到 注册中心中
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

spring:
  application:
    name: ttxs-mq
  rabbitmq:
    host: 121.199.31.35
    username: root
    password: root
    port: 5672

aliyun:
  sms:
    accessKeyId: LTAIqZ0Qls3OCgG0
    accessKeySecret: 1AHI5UHXPPCKfCbSQBU3v7bkkkReHW
    templateCode: SMS_164512688
    signName: 雨季注册
