server:
  port: 9998
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka/
spring:
  application:
    name: nlxx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.31.35:3306/nlxx?characterEncoding=utf-8&useSSL=false
    username: wypawj
    password: 123
  redis:
    host: 121.199.31.35
  rabbitmq:
    host: 121.199.31.35
    username: root
    password: root
    port: 5672
  data:
    elasticsearch:
      cluster-nodes: 121.199.31.35:9300
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
debug: true
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static/,classpath:/templates/

mybatis:
  mapperLocations: classpath:mappers/*.xml


